# Generated by Django 3.0.5 on 2020-06-17 21:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=100)),
                ('num_of_students', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('first_name', models.CharField(max_length=100, verbose_name='Firstname')),
                ('last_name', models.CharField(max_length=100, verbose_name='Lastname')),
                ('other_names', models.CharField(blank=True, max_length=100, verbose_name='Other Names')),
                ('student_image', models.ImageField(default='default.jpg', upload_to='student_images')),
                ('guardians_name', models.CharField(blank=True, max_length=150, verbose_name='Name Of Guardian')),
            ],
        ),
        migrations.CreateModel(
            name='TeachersProfile',
            fields=[
                ('teachers', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('first_name', models.CharField(max_length=100, verbose_name='Firstname')),
                ('last_name', models.CharField(max_length=100, verbose_name='Lastname')),
                ('other_names', models.CharField(max_length=100, verbose_name='Other Names')),
                ('teacher_image', models.ImageField(default='default.jpg', upload_to='teachers_images')),
                ('full_name', models.CharField(blank=True, max_length=100, verbose_name='Full name')),
                ('qualification', models.CharField(choices=[('bsc', 'Bsc'), ('msc', 'Msc'), ('phd', 'Phd')], max_length=100, verbose_name='Qualification')),
                ('relationship', models.CharField(choices=[('single', 'Single'), ('married', 'Married')], max_length=100, verbose_name='Relationship Status')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=100)),
                ('students', models.ManyToManyField(to='users.StudentProfile')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Classes')),
                ('teachers', models.ManyToManyField(to='users.TeachersProfile')),
            ],
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='teachers',
            field=models.ManyToManyField(to='users.TeachersProfile'),
        ),
        migrations.AddField(
            model_name='classes',
            name='student',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.StudentProfile'),
        ),
        migrations.AddField(
            model_name='classes',
            name='teachers',
            field=models.ManyToManyField(to='users.TeachersProfile'),
        ),
    ]
