# Generated by Django 3.0.5 on 2020-06-17 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200617_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.StudentProfile'),
        ),
    ]
