# Generated by Django 3.0.5 on 2020-06-17 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200617_2149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classes',
            name='student',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='my_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Classes'),
        ),
    ]
