# Generated by Django 3.0.5 on 2020-06-18 19:42

from django.db import migrations


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('users', '0005_auto_20200617_2155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teachersprofile',
            old_name='teachers',
            new_name='teacher',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='teachersprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='teachersprofile',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='teachersprofile',
            name='last_name',
        ),
    ]
