# Generated by Django 3.0.5 on 2020-06-18 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200618_1942'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classes',
            options={'verbose_name_plural': 'Classes'},
        ),
        migrations.AlterModelOptions(
            name='studentprofile',
            options={'verbose_name_plural': 'Student Profile'},
        ),
        migrations.AlterModelOptions(
            name='subjects',
            options={'verbose_name_plural': 'Subjects'},
        ),
        migrations.AlterModelOptions(
            name='teachersprofile',
            options={'verbose_name_plural': 'Teachers Profiles'},
        ),
        migrations.AlterField(
            model_name='classes',
            name='num_of_students',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='classes',
            name='teachers',
            field=models.ManyToManyField(blank=True, to='users.TeachersProfile'),
        ),
    ]
