# Generated by Django 3.0.5 on 2020-06-18 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20200618_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='teachers',
            field=models.ManyToManyField(blank=True, to='users.TeachersProfile'),
        ),
    ]
