# Generated by Django 3.0.5 on 2020-06-18 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20200618_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='my_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Classes'),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='teachers',
            field=models.ManyToManyField(blank=True, to='users.TeachersProfile'),
        ),
    ]
