# Generated by Django 3.0.5 on 2020-06-24 12:02

from django.db import migrations


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('users', '0012_auto_20200620_2135'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Classes',
            new_name='Class',
        ),
    ]
