# Generated by Django 3.0.5 on 2020-06-24 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveysystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachersprofile',
            name='qualification',
            field=models.CharField(choices=[('Bsc', 'Bsc'), ('Msc', 'Msc'), ('Phd', 'Phd')], max_length=100, verbose_name='Qualification'),
        ),
    ]
