# Generated by Django 3.0.5 on 2020-06-24 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveysystem', '0002_auto_20200624_1433'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.RemoveField(
            model_name='surveyinfo',
            name='teacher',
        ),
        migrations.AddField(
            model_name='surveyinfo',
            name='teacher',
            field=models.ManyToManyField(to='surveysystem.Class'),
        ),
    ]
