# Generated by Django 3.0.5 on 2020-06-24 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveysystem', '0003_auto_20200624_1443'),
    ]

    operations = [
        migrations.RenameField(
            model_name='surveyinfo',
            old_name='teacher',
            new_name='classes',
        ),
        migrations.AlterField(
            model_name='subjects',
            name='classes',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='surveysystem.Class'),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='students',
            field=models.ManyToManyField(blank=True, to='surveysystem.StudentProfile'),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='subject_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='surveyanswers',
            name='survey_question',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='surveysystem.SurveyQ'),
        ),
    ]
