# Generated by Django 3.0.5 on 2020-06-24 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveysystem', '0004_auto_20200624_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='num_of_students',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
