# Generated by Django 3.0.5 on 2020-06-24 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveysystem', '0005_auto_20200624_1559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjects',
            name='students',
        ),
        migrations.RemoveField(
            model_name='surveyinfo',
            name='classes',
        ),
        migrations.AddField(
            model_name='surveyinfo',
            name='teacher',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='surveysystem.TeachersProfile'),
        ),
    ]
