# Generated by Django 3.0.5 on 2020-06-24 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveysystem', '0007_auto_20200624_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyinfo',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='surveysystem.TeachersProfile'),
        ),
    ]
