# Generated by Django 3.0.5 on 2020-06-26 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveysystem', '0010_auto_20200626_1747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveyanswers',
            name='survey_textarea_answer',
        ),
        migrations.AlterField(
            model_name='surveyinfo',
            name='survey_textarea_question',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.CreateModel(
            name='SurveyTextareaAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey_textarea_answer', models.TextField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='surveysystem.StudentProfile')),
                ('survey', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='surveysystem.SurveyInfo')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='surveysystem.TeachersProfile')),
            ],
        ),
    ]
