# Generated by Django 3.0.5 on 2020-06-26 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveysystem', '0011_auto_20200626_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveytextareaanswer',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='surveysystem.SurveyInfo'),
        ),
    ]
