# Generated by Django 3.0.5 on 2020-06-26 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveysystem', '0012_auto_20200626_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveytextareaanswer',
            name='surveyq',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='surveysystem.SurveyQ'),
        ),
        migrations.AlterField(
            model_name='surveytextareaanswer',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='surveysystem.StudentProfile'),
        ),
        migrations.AlterField(
            model_name='surveytextareaanswer',
            name='survey',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='surveysystem.SurveyInfo'),
        ),
        migrations.AlterField(
            model_name='surveytextareaanswer',
            name='teacher',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='surveysystem.TeachersProfile'),
        ),
    ]
