# Generated by Django 3.0.5 on 2020-06-26 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveysystem', '0015_auto_20200626_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyq',
            name='survey_info',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='surveysystem.SurveyInfo'),
        ),
    ]
