# Generated by Django 3.0.5 on 2020-06-24 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey_image', models.ImageField(default='default.png', upload_to='survey_images')),
                ('survey_title', models.CharField(max_length=100)),
                ('survey_info', models.TextField()),
                ('survey_textarea_question', models.CharField(default='1', max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Survey Info',
            },
        ),
        migrations.CreateModel(
            name='SurveyQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey_question', models.CharField(max_length=500)),
                ('survey_info', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='survey.SurveyInfo')),
            ],
            options={
                'verbose_name_plural': 'Survey Questions',
            },
        ),
        migrations.CreateModel(
            name='SurveyChoices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(max_length=100)),
                ('survey_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.SurveyQ')),
            ],
        ),
        migrations.CreateModel(
            name='SurveyAnswers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('normal_answer', models.CharField(blank=True, max_length=100, null=True)),
                ('survey_textarea_answer', models.CharField(blank=True, max_length=100, null=True)),
                ('survey_question', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='survey.SurveyQ')),
            ],
        ),
    ]
